disabled_rules:
  - identifier_name
  - file_length
  - type_body_length
  - line_length
  - force_cast
  - trailing_comma
  - function_body_length
  - large_tuple
  - non_optional_string_data_conversion

opt_in_rules: []

excluded:
  - build
  - Carthage
  - Pods
  - .build
